[build-system]
requires = ["scikit-build-core", "numpy"]
build-backend = "scikit_build_core.build"

[project]
name = "pysurf96"
version = "0.0.1"
description = "Surface Wave Dispersion Python Wrapper for surf96."
requires-python = ">=3.8"
readme = "README.md"
authors = [{ name = "Marius Paul Isken", email = "mi@gfz-potsdam.de" }]
maintainers = [{ name = "Marius Paul Isken", email = "mi@gfz-potsdam.de" }]
keywords = ["InSAR", "satellite", "radar", "earthquake", "optimization"]
classifiers = [
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Atmospheric Science",
    "Topic :: Scientific/Engineering :: Image Recognition",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Visualization",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: C",
    "Operating System :: POSIX",
    "Operating System :: MacOS",
]
dependencies = ["numpy"]
